#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]


INTERESTING_EVENTS = {"ack", "stage", "preview", "reasoning", "draft_ready", "done", "error"}
RECOMMENDATION_OPTIONS = [
    "approve_story_continuity",
    "request_continuation_repair",
    "request_world_status_repair",
    "request_outline_replan",
    "block_story_conflict",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Route a rolling quality-gate review packet to review_agent.")
    parser.add_argument("--packet", required=True, help="Review packet JSON generated by rolling_chapter_production.py.")
    parser.add_argument("--book-id", default="", help="Book id override. Defaults to packet book_id.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8000", help="Local Flask backend URL.")
    parser.add_argument("--thread-id", default="", help="Local review thread id.")
    parser.add_argument("--output", required=True, help="NDJSON evidence output path.")
    parser.add_argument("--call-output", default="", help="Optional JSON payload evidence path.")
    parser.add_argument("--timeout", type=int, default=1800, help="HTTP timeout seconds.")
    return parser.parse_args()


def _compact_packet(packet: dict[str, Any]) -> dict[str, Any]:
    gate = packet.get("gate") if isinstance(packet.get("gate"), dict) else {}
    repair_delta = packet.get("repair_delta") if isinstance(packet.get("repair_delta"), dict) else {}
    review_route = packet.get("review_route") if isinstance(packet.get("review_route"), dict) else {}
    unlock_policy = packet.get("unlock_policy") if isinstance(packet.get("unlock_policy"), dict) else {}
    review_scope = packet.get("review_scope") if isinstance(packet.get("review_scope"), dict) else {}
    style_advisory = packet.get("style_advisory") if isinstance(packet.get("style_advisory"), dict) else {}
    no_prose_boundary = (
        packet.get("no_prose_boundary")
        if isinstance(packet.get("no_prose_boundary"), dict)
        else {}
    )
    cursor = packet.get("cursor") if isinstance(packet.get("cursor"), dict) else {}
    return {
        "schema_version": packet.get("schema_version"),
        "packet_type": packet.get("packet_type"),
        "packet_id": packet.get("packet_id"),
        "book_id": packet.get("book_id"),
        "chapter_number": packet.get("chapter_number"),
        "cursor": {
            "written_chapter_numbers": cursor.get("written_chapter_numbers"),
            "pending_card_numbers": cursor.get("pending_card_numbers"),
            "selected_card_numbers": cursor.get("selected_card_numbers"),
            "outline_card_count": cursor.get("outline_card_count"),
            "written_chapter_count": cursor.get("written_chapter_count"),
        },
        "gate": {
            "next_action": gate.get("next_action"),
            "blocked_next_action": gate.get("blocked_next_action"),
            "stop_reason": gate.get("stop_reason"),
            "quality_gate_locked": gate.get("quality_gate_locked"),
            "quality_gate_reason": gate.get("quality_gate_reason"),
            "quality_gate_source": gate.get("quality_gate_source"),
            "quality_gate_summary": gate.get("quality_gate_summary"),
        },
        "review_scope": {
            "hard_checks": review_scope.get("hard_checks"),
            "advisory_inputs": review_scope.get("advisory_inputs"),
            "style_is_scheduler_advisory_only": review_scope.get("style_is_scheduler_advisory_only"),
            "review_agent_focus": review_scope.get("review_agent_focus"),
        },
        "style_advisory": {
            "active": style_advisory.get("active"),
            "can_block_scheduler": style_advisory.get("can_block_scheduler"),
            "revision_owner": style_advisory.get("revision_owner"),
            "summary": style_advisory.get("summary"),
        },
        "repair_delta": {
            "verdict": repair_delta.get("verdict"),
            "score": repair_delta.get("score"),
            "hard_failures": repair_delta.get("hard_failures"),
            "warnings": repair_delta.get("warnings"),
            "acceptance": repair_delta.get("acceptance"),
            "metric_deltas": repair_delta.get("metric_deltas"),
            "before_source": repair_delta.get("before_source"),
            "after_source": repair_delta.get("after_source"),
        },
        "review_route": {
            "agent_key": review_route.get("agent_key"),
            "target_file": review_route.get("target_file"),
            "writable_files": review_route.get("writable_files"),
            "forbidden_write_files": review_route.get("forbidden_write_files"),
            "recommendation_only": review_route.get("recommendation_only"),
        },
        "required_recommendation_options": packet.get("required_recommendation_options"),
        "unlock_policy": {
            "requires_explicit_human_unlock": unlock_policy.get("requires_explicit_human_unlock"),
            "review_recommendation_can_unlock": unlock_policy.get("review_recommendation_can_unlock"),
            "unlock_must_bind": unlock_policy.get("unlock_must_bind"),
        },
        "no_prose_boundary": {
            "packet_omits_chapter_draft_text": no_prose_boundary.get("packet_omits_chapter_draft_text"),
            "packet_omits_outline_card_fields": no_prose_boundary.get("packet_omits_outline_card_fields"),
            "prose_owner": no_prose_boundary.get("prose_owner"),
            "review_owner": no_prose_boundary.get("review_owner"),
            "human_unlock_owner": no_prose_boundary.get("human_unlock_owner"),
        },
    }


def build_review_intent(packet: dict[str, Any]) -> str:
    compact = _compact_packet(packet)
    packet_json = json.dumps(compact, ensure_ascii=False, sort_keys=True)
    chapter_number = compact.get("chapter_number") or "unknown"
    return (
        "R30-RB-2 rolling review bridge.\n"
        "You are the project review Agent. Review the existing chapter draft and context through tools only.\n"
        "Your hard review scope is plot continuity, world/status consistency, causal chain, chapter-card fulfillment, and unresolved WORLD_MODEL_REQUIRED risk.\n"
        "Style diagnostics are advisory hints for the author and continuation Agent, not scheduler locks and not approval criteria.\n"
        "Do not write, rewrite, replace, append, paste, or summarize novel prose into chapter_draft.md.\n"
        "If there is a reusable finding, you may write only to error_archive.md. If no durable finding is needed, do not write files.\n"
        "Your recommendation is advisory and cannot unlock the rolling scheduler. Only the human author can unlock.\n"
        f"Review target: Chapter {chapter_number}, active_file=chapter_draft.md.\n"
        "Return a concise structured recommendation with exactly one recommendation from this set: "
        f"{', '.join(RECOMMENDATION_OPTIONS)}.\n"
        "Also return: reason, risk_level, whether error_archive.md was written, and what human decision is required next.\n"
        "Do not include chapter prose in the final answer.\n\n"
        "NO-PROSE REVIEW PACKET JSON:\n"
        f"{packet_json}"
    )


def build_deduce_payload(packet: dict[str, Any], *, thread_id: str) -> dict[str, Any]:
    book_id = packet.get("book_id")
    if not isinstance(book_id, str) or not book_id.strip():
        raise ValueError("packet.book_id is required")
    chapter_number = packet.get("chapter_number")
    return {
        "book_id": book_id.strip(),
        "intent": build_review_intent(packet),
        "active_file": "chapter_draft.md",
        "file_type": "chapter",
        "route_agent_key": "review_agent",
        "thread_id": thread_id,
        "chapter_index": chapter_number if isinstance(chapter_number, int) else 0,
        "dify_user": "loregit-ui-rolling-review-bridge",
    }


def iter_sse_events(response: Iterable[bytes]):
    event_name = "message"
    data_lines: list[str] = []
    for raw_line in response:
        line = raw_line.decode("utf-8", errors="replace").rstrip("\n")
        if not line.strip():
            if data_lines:
                raw_data = "\n".join(data_lines)
                try:
                    data = json.loads(raw_data)
                except json.JSONDecodeError:
                    data = {"raw": raw_data}
                yield event_name, data
            event_name = "message"
            data_lines = []
            continue
        if line.startswith("event:"):
            event_name = line.split(":", 1)[1].strip() or "message"
        elif line.startswith("data:"):
            data_lines.append(line.split(":", 1)[1].lstrip())


def compact_event(event_name: str, data: Any) -> dict[str, Any]:
    if not isinstance(data, dict):
        return {"event": event_name, "data_type": type(data).__name__}
    if event_name == "ack":
        return {
            "event": event_name,
            "status": data.get("status"),
            "book_id": data.get("book_id"),
            "thread_id": data.get("thread_id"),
            "file_name": data.get("file_name"),
            "active_file": data.get("active_file"),
            "file_type": data.get("file_type"),
            "write_scope": data.get("write_scope"),
            "branch": data.get("branch"),
            "routed_agent": data.get("routed_agent"),
            "base_etag": data.get("base_etag"),
        }
    if event_name == "draft_ready":
        return {
            "event": event_name,
            "book_id": data.get("book_id"),
            "file_name": data.get("file_name"),
            "branch": data.get("branch"),
            "commit_id": data.get("commit_id"),
            "draft_changed": data.get("draft_changed"),
            "changed_files": data.get("changed_files"),
            "content_chars": len(data.get("content") or ""),
            "diff_preview_chars": len(data.get("diff_preview") or ""),
        }
    if event_name == "done":
        answer = data.get("answer") or ""
        return {
            "event": event_name,
            "status": data.get("status"),
            "book_id": data.get("book_id"),
            "thread_id": data.get("thread_id"),
            "file_name": data.get("file_name"),
            "branch": data.get("branch"),
            "conversation_id": data.get("conversation_id"),
            "upstream_conversation_id": data.get("upstream_conversation_id"),
            "task_id": data.get("task_id"),
            "draft_changed": data.get("draft_changed"),
            "write_confirmed": data.get("write_confirmed"),
            "review_target_file": data.get("review_target_file"),
            "changed_files": data.get("changed_files"),
            "hidden_payload_detected": data.get("hidden_payload_detected"),
            "hidden_payload_valid": data.get("hidden_payload_valid"),
            "sync_status": data.get("sync_status"),
            "sync_commit_id": data.get("sync_commit_id"),
            "answer_chars": len(answer),
        }
    if event_name == "stage":
        return {
            "event": event_name,
            "stage_code": data.get("stage_code"),
            "stage_text": data.get("stage_text"),
            "source_event": data.get("source_event"),
            "node_title": data.get("node_title"),
            "node_type": data.get("node_type"),
            "task_id": data.get("task_id"),
        }
    if event_name == "reasoning":
        text = data.get("text") or ""
        return {
            "event": event_name,
            "label": data.get("label"),
            "status": data.get("status"),
            "source_event": data.get("source_event"),
            "text_chars": len(text),
        }
    if event_name == "preview":
        text = data.get("text") or data.get("answer") or data.get("content") or ""
        return {
            "event": event_name,
            "status": data.get("status"),
            "source_event": data.get("source_event"),
            "text_chars": len(text),
        }
    if event_name == "error":
        return {
            "event": event_name,
            "code": data.get("code"),
            "message": data.get("message"),
            "status": data.get("status"),
            "thread_id": data.get("thread_id") or data.get("conversation_id"),
            "task_id": data.get("task_id"),
        }
    return {"event": event_name, "keys": sorted(data.keys())}


def main() -> int:
    args = parse_args()
    packet_path = Path(args.packet)
    if not packet_path.is_absolute():
        packet_path = ROOT / packet_path
    packet = json.loads(packet_path.read_text(encoding="utf-8"))
    if not isinstance(packet, dict):
        raise SystemExit("packet JSON must be an object")
    book_id = args.book_id.strip() or str(packet.get("book_id") or "").strip()
    if not book_id:
        raise SystemExit("book_id is required")
    thread_id = args.thread_id.strip() or f"r30_review_bridge_ch{packet.get('chapter_number') or 'x'}"
    payload = build_deduce_payload({**packet, "book_id": book_id}, thread_id=thread_id)

    call_output = Path(args.call_output) if args.call_output else None
    if call_output is not None:
        if not call_output.is_absolute():
            call_output = ROOT / call_output
        call_output.parent.mkdir(parents=True, exist_ok=True)
        call_output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = ROOT / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)

    req = urllib.request.Request(
        f"{args.base_url.rstrip('/')}/api/world/deduce_stream?book_id={book_id}",
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with output_path.open("w", encoding="utf-8", newline="\n") as out:
            with urllib.request.urlopen(req, timeout=max(1, args.timeout)) as response:
                for event_name, data in iter_sse_events(response):
                    if event_name not in INTERESTING_EVENTS:
                        continue
                    line = json.dumps(compact_event(event_name, data), ensure_ascii=False)
                    out.write(line + "\n")
                    out.flush()
                    print(line, flush=True)
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        line = json.dumps({"status": "http_error", "code": exc.code, "body_chars": len(body)}, ensure_ascii=False)
        with output_path.open("a", encoding="utf-8", newline="\n") as out:
            out.write(line + "\n")
        print(line)
        return 1
    except Exception as exc:
        line = json.dumps({"status": "error", "message": str(exc)}, ensure_ascii=False)
        with output_path.open("a", encoding="utf-8", newline="\n") as out:
            out.write(line + "\n")
        print(line)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
